In [3]:
import numpy as np
a = np.array([[1, 2, 4], [5, 8, 7]])
print ("Array created using passed list:\n", a)

Array created using passed list:
 [[1 2 4]
 [5 8 7]]


In [4]:
# Creating a 3X4 array with all zeros
b = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", b)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
#Create a constant value array of complex type
c = np.full((3, 3), 6)
print ("\nAn array initialized with all 6s.\n", c)


An array initialized with all 6s.
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [2]:
#Create an array with random values
import numpy as np
d = np.random.random((2, 2))
print ("\nA random array:\n", d)


A random array:
 [[0.64709117 0.33067272]
 [0.67694076 0.59917793]]


In [3]:
# Create a sequence of integers from 0 to 30 with steps of 5
e = np.arange(0, 30, 5)
print ("\n A sequential array with steps of 5:\n", e)


 A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [5]:
#Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4], [5, 2, 4, 2],[1, 2, 0, 1]])
newarr = arr.reshape(4, 3)
print ("\nOriginal array:\n", arr)
print ("Reshaped array[4,3]:\n", newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [6]:
#Flatten array
flarr= arr.flatten()
print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Fattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [12]:
#Dimension of the array
print(arr.ndim)

2


In [13]:
#Shape of the array
print(arr.shape)

(3, 4)


In [15]:
#Size of the array
print(arr.size)

12


In [16]:
#Datatype of the array
print(arr.dtype)

int32


In [18]:
#Convert the datatype from int to float
c=arr.astype('f')
print(c)
b=arr.astype('i')
print(b)


[[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]


In [19]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]


In [20]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[2,0:2])

[7 8]


In [21]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[2:,2:])

[[ 9]
 [12]
 [15]]


In [22]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:,3:])

[]


In [23]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[:,1])

[ 2  5  8 11 14]


In [24]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
c=p.astype('f')
print(c)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]


In [ ]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
c=p.astype('i')
print(c)